/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package x.pkg0;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author elkin
 */
public class Main_x0 extends javax.swing.JFrame {

    private boolean ganar = false;
    private boolean x = true;
    private boolean o = false;
    private int turnos = 0;
    JLabel[] lineas;
    public int xJuegos = 0;
    public int oJuegos = 0;

    public void botones() {
        lineas = new JLabel[9];
        lineas[0] = B1;
        lineas[1] = B2;
        lineas[2] = B3;
        lineas[3] = B4;
        lineas[4] = B5;
        lineas[5] = B6;
        lineas[6] = B7;
        lineas[7] = B8;
        lineas[8] = B9;

    }

    public int clicks(int casilla) {
        if (!lineas[casilla].getText().equals("X") && !lineas[casilla].getText().equals("O")) {
            if (x) {
                lineas[casilla].setText("X");
                x = false;
                o = true;
                turnos++;
                ganador();
                return turnos;
            } else if (o) {
                lineas[casilla].setText("O");
                x = true;
                o = false;
                turnos++;
                ganador();
                return turnos;
            }
        }
        return 0;
    }

    public int ganador() {
        int[][] combinaciones = {
            {0, 1, 2}, {3, 4, 5}, {6, 7, 8},
            {0, 3, 6}, {1, 4, 7}, {2, 5, 8},
            {0, 4, 8}, {2, 4, 6}
        };

        for (int[] combo : combinaciones) {
            if (!lineas[combo[0]].getText().isEmpty()
                    && lineas[combo[0]].getText().equals(lineas[combo[1]].getText())
                    && lineas[combo[1]].getText().equals(lineas[combo[2]].getText())) {

                this.ganar = true;
                String simboloGanador = lineas[combo[0]].getText();

                if (simboloGanador.equals("X")) {
                    xJuegos++;
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Ha ganado el jugador X!");
                } else if (simboloGanador.equals("O")) {
                    oJuegos++;
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Ha ganado el jugador O!");
                }
                
                //ELECCION
                    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                            this,
                            "¿Deseas jugar otra partida?",
                            "Fin del Juego",
                            javax.swing.JOptionPane.YES_NO_OPTION);
                    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> reiniciar());
                        timer.setRepeats(false);
                        timer.start();
                    } else {
                        System.exit(0);
                        if (simboloGanador.equals("O")) {
                            return oJuegos;
                        } else if (simboloGanador.equals("X")) {
                            return xJuegos;
                        }
                    }

                resaltarLineaGanadora(combo[0], combo[1], combo[2]);

            }
        }

        if (!this.ganar && this.turnos == 9) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Es un empate!");
            this.ganar = true;

            javax.swing.Timer timer = new javax.swing.Timer(2000, e -> reiniciar());
            timer.setRepeats(false);
            timer.start();
        }
        return 0;
    }

    private void resaltarLineaGanadora(int a, int b, int c) {
        lineas[a].setBackground(java.awt.Color.GREEN);
        lineas[b].setBackground(java.awt.Color.GREEN);
        lineas[c].setBackground(java.awt.Color.GREEN);
    }

    private void reiniciar() {
        ganar = false;
        turnos = 0;
        x = true;
        o = false;

        for (int i = 0; i < lineas.length; i++) {
            lineas[i].setText("");
            lineas[i].setBackground(java.awt.Color.WHITE);
        }
    }

    public Main_x0() {
        initComponents();
        this.setLocationRelativeTo(null);
        botones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        B8 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B9 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        B8.setBackground(new java.awt.Color(255, 255, 255));
        B8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B8.setOpaque(true);
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B8MousePressed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B7.setOpaque(true);
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B7MousePressed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setOpaque(true);
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B1MousePressed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5.setOpaque(true);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B5MousePressed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setOpaque(true);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B4MousePressed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B6.setOpaque(true);
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B6MousePressed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setOpaque(true);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B2MousePressed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(255, 255, 255));
        B9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B9.setOpaque(true);
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B9MousePressed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setOpaque(true);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                B3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MousePressed
        clicks(8);
    }//GEN-LAST:event_B9MousePressed

    private void B8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MousePressed
        clicks(7);
    }//GEN-LAST:event_B8MousePressed

    private void B7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MousePressed

        clicks(6);
    }//GEN-LAST:event_B7MousePressed

    private void B1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MousePressed
        clicks(0);
    }//GEN-LAST:event_B1MousePressed

    private void B5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MousePressed
        clicks(4);
    }//GEN-LAST:event_B5MousePressed

    private void B4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MousePressed
        clicks(3);
    }//GEN-LAST:event_B4MousePressed

    private void B3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MousePressed
        clicks(2);
    }//GEN-LAST:event_B3MousePressed

    private void B6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MousePressed
        clicks(5);
    }//GEN-LAST:event_B6MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed

    }//GEN-LAST:event_jLabel10MousePressed

    private void B2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MousePressed
        clicks(1);
    }//GEN-LAST:event_B2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_x0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_x0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_x0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_x0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_x0().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel B1;
    public javax.swing.JLabel B2;
    public javax.swing.JLabel B3;
    public javax.swing.JLabel B4;
    public javax.swing.JLabel B5;
    public javax.swing.JLabel B6;
    public javax.swing.JLabel B7;
    public javax.swing.JLabel B8;
    public javax.swing.JLabel B9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
